import argparse
import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Tuple

import openpyxl


@dataclass
class StudentRow:
    roll_no: str
    name: str
    email: str


def norm(v: Any) -> str:
    if v is None:
        return ""
    return str(v).strip()


def norm_key(s: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "", norm(s).lower())


def find_header_row(ws, max_scan_rows: int = 20) -> Tuple[int, List[str]]:
    for i, row in enumerate(ws.iter_rows(min_row=1, max_row=max_scan_rows, values_only=True), start=1):
        keys = [norm_key(v) for v in row]
        if any(k in ("rollnos", "rollno", "rollnumber", "rollnumbers") for k in keys) and any(
            k in ("names", "name") for k in keys
        ):
            return i, [norm(v) for v in row]
    # Fall back to the first row (common for simple sheets)
    header = [norm(v) for v in next(ws.iter_rows(min_row=1, max_row=1, values_only=True))]
    return 1, header


def header_index(header: List[str]) -> Dict[str, int]:
    idx: Dict[str, int] = {}
    for i, h in enumerate(header):
        k = norm_key(h)
        if k:
            idx[k] = i
    return idx


def pick_col(idx: Dict[str, int], *candidates: str) -> Optional[int]:
    for c in candidates:
        if c in idx:
            return idx[c]
    return None


def iter_students_from_sheet(ws, email_domain: str) -> Iterable[StudentRow]:
    header_row, header = find_header_row(ws)
    idx = header_index(header)

    c_roll = pick_col(idx, "rollnos", "rollno", "rollnumber", "rollnumbers")
    c_name = pick_col(idx, "names", "name")
    c_email = pick_col(idx, "mailids", "mailid", "email", "emailid")

    if c_roll is None or c_name is None:
        raise ValueError(f"Missing required columns (roll/name) in sheet '{ws.title}'")

    for row in ws.iter_rows(min_row=header_row + 1, values_only=True):
        roll = norm(row[c_roll] if c_roll < len(row) else None)
        name = norm(row[c_name] if c_name < len(row) else None)
        email = norm(row[c_email] if c_email is not None and c_email < len(row) else None)

        if not roll or not name:
            continue

        roll_clean = re.sub(r"\s+", "", roll)
        if not email:
            email = f"{roll_clean.lower()}@{email_domain}".lower()

        yield StudentRow(roll_no=roll_clean, name=name, email=email.lower())


def load_students_from_xlsx(path: str, email_domain: str) -> List[StudentRow]:
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb[wb.sheetnames[0]]
    return list(iter_students_from_sheet(ws, email_domain=email_domain))


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def emit_upsert_sql(rows: List[StudentRow], *, include_transaction: bool = True, include_extension: bool = True) -> str:
    out: List[str] = []
    out.append("-- Generated by import_students_xlsx.py")
    if include_transaction:
        out.append("BEGIN;")
    if include_extension:
        out.append("-- Ensure pgcrypto exists for crypt()/gen_salt().")
        out.append("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # Deduplicate by email; keep the first non-empty values.
    by_email: Dict[str, StudentRow] = {}
    for r in rows:
        if not r.email:
            continue
        if r.email not in by_email:
            by_email[r.email] = r
            continue
        prev = by_email[r.email]
        by_email[r.email] = StudentRow(
            roll_no=r.roll_no or prev.roll_no,
            name=r.name or prev.name,
            email=r.email,
        )

    for email, r in sorted(by_email.items(), key=lambda kv: kv[0]):
        email_lit = sql_quote(email)
        roll_lit = sql_quote(r.roll_no)
        name_lit = sql_quote(r.name)
        pwd_lit = sql_quote(r.roll_no)

        out.append("")
        out.append(f"-- {email}")
        out.append(
            "INSERT INTO users (email, password_hash, name, approved)"
            f" VALUES ({email_lit}, crypt({pwd_lit}, gen_salt('bf')), {name_lit}, TRUE)"
            " ON CONFLICT (email) DO UPDATE SET"
            "   name = EXCLUDED.name,"
            "   password_hash = EXCLUDED.password_hash,"
            "   approved = TRUE;"
        )
        out.append(
            "INSERT INTO user_roles (user_id, role)"
            f" SELECT id, 'student' FROM users WHERE email = {email_lit}"
            " ON CONFLICT (user_id, role) DO NOTHING;"
        )
        out.append(
            "INSERT INTO profiles (user_id, name, roll_no, available)"
            f" SELECT id, {name_lit}, {roll_lit}, TRUE FROM users WHERE email = {email_lit}"
            " ON CONFLICT (user_id) DO UPDATE SET"
            "   name = EXCLUDED.name,"
            "   roll_no = EXCLUDED.roll_no,"
            "   available = EXCLUDED.available;"
        )

    if include_transaction:
        out.append("")
        out.append("COMMIT;")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate SQL to import students from .xlsx into the Alumni Link DB schema.")
    ap.add_argument("xlsx", nargs="+", help="Path(s) to .xlsx files")
    ap.add_argument("--email-domain", default="bvrithyderabad.edu.in", help="Email domain to use if email is missing")
    ap.add_argument(
        "--flyway",
        action="store_true",
        help="Emit SQL suitable for a Flyway migration (no BEGIN/COMMIT, no CREATE EXTENSION).",
    )
    ap.add_argument(
        "--out",
        help="Write output to a file as UTF-8 (recommended on Windows to avoid UTF-16 redirects).",
    )
    args = ap.parse_args()

    all_rows: List[StudentRow] = []
    for p in args.xlsx:
        all_rows.extend(load_students_from_xlsx(p, email_domain=args.email_domain))

    sql = emit_upsert_sql(
        all_rows,
        include_transaction=not args.flyway,
        include_extension=not args.flyway,
    )
    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(sql)
    else:
        print(sql, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
