import argparse
import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Tuple

import openpyxl


@dataclass
class AlumniRow:
    roll_no: str
    name: str
    department: str
    company: str
    package_lpa: Optional[float]
    admission_year: Optional[int]


def norm(s: Any) -> str:
    if s is None:
        return ""
    return str(s).strip()


def norm_key(s: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "", norm(s).lower())


def parse_year(s: str) -> Optional[int]:
    s = norm(s)
    if not s:
        return None
    m = re.search(r"\b(19\d{2}|20\d{2})\b", s)
    if m:
        return int(m.group(1))
    m = re.search(r"\b(\d{2})\b", s)
    if m:
        yy = int(m.group(1))
        return 2000 + yy if yy < 80 else 1900 + yy
    return None


def parse_package(v: Any) -> Optional[float]:
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return float(v)
    s = norm(v)
    if not s:
        return None
    # Handles "32.76", "32.76 LPA", "CTC 10.5", etc.
    m = re.search(r"(\d+(?:\.\d+)?)", s.replace(",", ""))
    if not m:
        return None
    try:
        return float(m.group(1))
    except ValueError:
        return None


def guess_batch(admission_year: Optional[int], roll_no: str) -> Optional[str]:
    y = admission_year
    if y is None:
        m = re.match(r"^\s*(\d{2})", roll_no)
        if m:
            y = 2000 + int(m.group(1))
    if y is None:
        return None
    return f"{y}-{y + 4}"


def find_header_row(ws, max_scan_rows: int = 50) -> Tuple[int, List[str]]:
    # Look for a row that contains a roll number column.
    for i, row in enumerate(ws.iter_rows(min_row=1, max_row=max_scan_rows, values_only=True), start=1):
        keys = [norm_key(v) for v in row]
        if any(k in ("rollno", "rollnumber", "registrationenrollmentnoofthestudentinyourinstitution") for k in keys):
            return i, [norm(v) for v in row]
        if any("registrationenrollment" in k for k in keys) and any("name" in k for k in keys):
            return i, [norm(v) for v in row]
    raise ValueError(f"Could not find header row in sheet '{ws.title}'")


def header_index(header: List[str]) -> Dict[str, int]:
    idx: Dict[str, int] = {}
    for i, h in enumerate(header):
        k = norm_key(h)
        if not k:
            continue
        idx[k] = i
    return idx


def pick_col(idx: Dict[str, int], *candidates: str) -> Optional[int]:
    for c in candidates:
        if c in idx:
            return idx[c]
    return None


def iter_alumni_rows_from_sheet(ws) -> Iterable[AlumniRow]:
    header_row, header = find_header_row(ws)
    idx = header_index(header)

    c_roll = pick_col(idx, "rollno", "rollnumber", "registrationenrollmentnoofthestudentinyourinstitution")
    c_name = pick_col(idx, "name", "nameofthestudent")
    c_dept = pick_col(idx, "dept", "department")
    c_company = pick_col(idx, "company", "placedcompany", "organizationplacedin")
    c_pkg = pick_col(idx, "salary", "salaryofferedlpa", "ctc", "package")
    c_adm = pick_col(idx, "yearofadmission")

    if c_roll is None or c_name is None:
        raise ValueError(f"Missing required columns (roll/name) in sheet '{ws.title}'")

    for row in ws.iter_rows(min_row=header_row + 1, values_only=True):
        roll = norm(row[c_roll] if c_roll < len(row) else None)
        name = norm(row[c_name] if c_name < len(row) else None)
        if not roll or not name:
            continue

        dept = norm(row[c_dept] if c_dept is not None and c_dept < len(row) else None)
        company = norm(row[c_company] if c_company is not None and c_company < len(row) else None)
        pkg = parse_package(row[c_pkg] if c_pkg is not None and c_pkg < len(row) else None)
        adm_year = parse_year(row[c_adm] if c_adm is not None and c_adm < len(row) else None)

        yield AlumniRow(
            roll_no=roll,
            name=name,
            department=dept,
            company=company,
            package_lpa=pkg,
            admission_year=adm_year,
        )


def load_alumni_from_xlsx(path: str) -> List[AlumniRow]:
    wb = openpyxl.load_workbook(path, data_only=True)
    # Use the first sheet by default (your files put alumni data there)
    ws = wb[wb.sheetnames[0]]
    return list(iter_alumni_rows_from_sheet(ws))


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def emit_upsert_sql(rows: List[AlumniRow], email_domain: str) -> str:
    out: List[str] = []
    out.append("-- Generated by import_alumni_xlsx.py")
    out.append("BEGIN;")
    out.append("-- Ensure pgcrypto exists for crypt()/gen_salt().")
    out.append("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # Deduplicate by email; prefer non-empty fields and higher package.
    by_email: Dict[str, AlumniRow] = {}
    for r in rows:
        roll_clean = re.sub(r"\\s+", "", r.roll_no)
        if not roll_clean:
            continue
        email = f"{roll_clean.lower()}@{email_domain}".lower()
        prev = by_email.get(email)
        if prev is None:
            by_email[email] = r
            continue
        merged = AlumniRow(
            roll_no=roll_clean if roll_clean else prev.roll_no,
            name=r.name or prev.name,
            department=r.department or prev.department,
            company=r.company or prev.company,
            package_lpa=max([x for x in [prev.package_lpa, r.package_lpa] if x is not None], default=None),
            admission_year=r.admission_year or prev.admission_year,
        )
        by_email[email] = merged

    for email, r in sorted(by_email.items(), key=lambda kv: kv[0]):
        roll_clean = re.sub(r"\\s+", "", r.roll_no)
        batch = guess_batch(r.admission_year, roll_clean)
        pkg = r.package_lpa

        # Use roll number as the initial password (bcrypt via pgcrypto crypt()).
        # This keeps passwords unique without hardcoding a single shared password.
        pwd_literal = sql_quote(roll_clean.lower())
        email_lit = sql_quote(email)
        name_lit = sql_quote(r.name)
        dept_lit = sql_quote(r.department) if r.department else "''"
        company_lit = sql_quote(r.company) if r.company else "''"
        roll_lit = sql_quote(roll_clean)
        batch_lit = sql_quote(batch) if batch else "''"
        pkg_lit = "NULL" if pkg is None else str(pkg)

        out.append("")
        out.append(f"-- {email}")
        out.append(
            "INSERT INTO users (email, password_hash, name, approved)"
            f" VALUES ({email_lit}, crypt({pwd_literal}, gen_salt('bf')), {name_lit}, TRUE)"
            " ON CONFLICT (email) DO UPDATE SET"
            "   name = EXCLUDED.name,"
            "   approved = TRUE;"
        )
        out.append(
            "INSERT INTO user_roles (user_id, role)"
            f" SELECT id, 'alumni' FROM users WHERE email = {email_lit}"
            " ON CONFLICT (user_id, role) DO NOTHING;"
        )
        out.append(
            "INSERT INTO profiles (user_id, name, roll_no, department, company, package_amount, batch, available)"
            f" SELECT id, {name_lit}, {roll_lit}, {dept_lit}, {company_lit}, {pkg_lit}, {batch_lit}, TRUE"
            f" FROM users WHERE email = {email_lit}"
            " ON CONFLICT (user_id) DO UPDATE SET"
            "   name = EXCLUDED.name,"
            "   roll_no = EXCLUDED.roll_no,"
            "   department = EXCLUDED.department,"
            "   company = EXCLUDED.company,"
            "   package_amount = EXCLUDED.package_amount,"
            "   batch = EXCLUDED.batch,"
            "   available = EXCLUDED.available;"
        )

    out.append("")
    out.append("COMMIT;")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate SQL to import alumni from .xlsx into the Alumni Link DB schema.")
    ap.add_argument("xlsx", nargs="+", help="Path(s) to .xlsx files")
    ap.add_argument("--email-domain", default="bvrithyderabad.edu.in", help="Email domain to use")
    args = ap.parse_args()

    all_rows: List[AlumniRow] = []
    for p in args.xlsx:
        all_rows.extend(load_alumni_from_xlsx(p))

    print(emit_upsert_sql(all_rows, args.email_domain), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
